#!/usr/bin/env python3
"""Extract MW3's shader recipes and DX9 bytecode from a user's app bundle.

No game, graphics driver, or shader compiler is launched. GLSL is generated by
MW3's translator at runtime; these outputs provide inputs to its preload path.
"""
import argparse
import collections
import hashlib
import json
from pathlib import Path
import plistlib
import re
import struct
import zlib


NAME = re.compile(rb'([A-Za-z0-9_]+\.hlsl)\x00')


def valid_tokens(tokens, stage):
    return (len(tokens) >= 8 and len(tokens) % 4 == 0
            and struct.unpack_from('<I', tokens)[0] >> 16 ==
            (0xfffe if stage == 'VS' else 0xffff)
            and tokens[-4:] == b'\xff\xff\0\0')


def add_hash_aliases(binaries, missing, aliases):
    for stage in ('VS', 'PS'):
        by_hash = collections.defaultdict(list)
        for uid, tokens in binaries[stage].items():
            by_hash[uid.split(':', 1)[0]].append((uid, tokens))
        for uid in sorted(missing[stage]):
            candidates = by_hash.get(uid.split(':', 1)[0], [])
            token_sets = {tokens for _, tokens in candidates}
            if len(token_sets) != 1:
                continue
            tokens = next(iter(token_sets))
            if not valid_tokens(tokens, stage) or zlib.adler32(tokens) != int(uid.split(':', 1)[0], 16):
                continue
            binaries[stage][uid] = tokens
            missing[stage].remove(uid)
            aliases.append({'stage': stage, 'uid': uid, 'source_uid': candidates[0][0],
                            'bytes': len(tokens), 'sha256': hashlib.sha256(tokens).hexdigest()})


def fastfile_payload(source):
    header = source.read(21)
    if header.startswith(b'IWffu100'):
        while chunk := source.read(65536):
            yield chunk
        return
    if not header.startswith(b'IWff0100') or source.read(8) != b'IWffs100':
        raise ValueError('Unsupported fastfile header')
    # Signed files pad their authentication header to 8192 bytes after the
    # 21-byte preamble. Each group then has one hash chunk and 256 data chunks.
    # Format reference: CoD-FF-Tools docs/MW2_PC_FastFile_Format.md.
    # Extraction validates the shader UID checksum rather than RSA signatures.
    source.seek(21 + 8192)
    while True:
        hashes = source.read(8192)
        if not hashes:
            return
        if len(hashes) != 8192:
            raise ValueError('Truncated signed fastfile hash chunk')
        remaining = 256 * 8192
        while remaining:
            chunk = source.read(min(65536, remaining))
            if not chunk:
                return
            remaining -= len(chunk)
            yield chunk
            if len(chunk) % 8192:
                return


def scan_fastfile(path, missing, binaries, extracted, target_hashes=None, hash_candidates=None):
    needed_names = {uid.split(':', 1)[1] for values in missing.values() for uid in values}
    collect_hashes = bool(target_hashes and any(target_hashes.values()))
    before = sum(map(len, missing.values()))
    expanded = maximum = base = 0
    buffer = b''
    decompressor = zlib.decompressobj()
    error = None
    seen = set()
    try:
        with path.open('rb') as source:
            payload = iter(fastfile_payload(source))
            compressed = b''
            while any(missing.values()) or collect_hashes:
                if not compressed:
                    compressed = next(payload, b'')
                if not compressed:
                    break
                chunk = decompressor.decompress(compressed, 65536)
                compressed = decompressor.unconsumed_tail
                expanded += len(chunk)
                buffer += chunk
                maximum = max(maximum, len(buffer))
                keep = max(0, len(buffer) - 512)
                for match in NAME.finditer(buffer):
                    at, name = match.start(), match.group(1).decode('ascii')
                    if at < 4 or (not collect_hashes and name not in needed_names):
                        continue
                    count = struct.unpack_from('<I', buffer, at - 4)[0]
                    start, end = match.end(), match.end() + count * 4
                    if not 0 < count < 65536:
                        continue
                    if end > len(buffer):
                        keep = min(keep, at - 4)
                        continue
                    absolute = base + start
                    if absolute in seen:
                        continue
                    seen.add(absolute)
                    tokens = buffer[start:end]
                    stage = 'VS' if tokens[2:4] == b'\xfe\xff' else 'PS'
                    if not valid_tokens(tokens, stage):
                        continue
                    checksum = zlib.adler32(tokens)
                    uid = f'{checksum:08x}:' + name
                    if collect_hashes and checksum in target_hashes.get(stage, set()):
                        digest = hashlib.sha256(tokens).hexdigest()
                        bucket = hash_candidates.setdefault((stage, checksum), {})
                        if digest not in bucket:
                            bucket[digest] = {'tokens': tokens, 'source_uid': uid,
                                              'zone': str(path), 'offset': absolute,
                                              'occurrences': 0}
                        bucket[digest]['occurrences'] += 1
                    if uid not in missing[stage]:
                        continue
                    binaries[stage][uid] = tokens
                    missing[stage].remove(uid)
                    extracted.append({'stage': stage, 'uid': uid, 'zone': str(path),
                                      'offset': absolute, 'token_count': count,
                                      'sha256': hashlib.sha256(tokens).hexdigest()})
                buffer = buffer[keep:]
                base += keep
                if decompressor.eof:
                    break
            if (any(missing.values()) or collect_hashes) and not decompressor.eof:
                raise ValueError('Truncated zlib stream')
    except (OSError, ValueError, zlib.error) as exc:
        error = str(exc)
    return {'file': str(path), 'expanded_bytes': expanded,
            'max_scan_buffer_bytes': maximum,
            'resolved': before - sum(map(len, missing.values())), 'error': error}


def add_scanned_checksum_aliases(binaries, missing, candidates, aliases):
    # Adler-32 is the engine's UID checksum, not a collision-resistant proof.
    # Accept only a single SHA-256-distinct bytecode sequence across every
    # scanned asset for this stage/checksum, and keep provenance explicit.
    for stage in ('VS', 'PS'):
        for uid in sorted(missing[stage]):
            bucket = candidates.get((stage, int(uid.split(':', 1)[0], 16)), {})
            if len(bucket) != 1:
                continue
            digest, candidate = next(iter(bucket.items()))
            tokens = candidate['tokens']
            if (not valid_tokens(tokens, stage)
                    or zlib.adler32(tokens) != int(uid.split(':', 1)[0], 16)
                    or hashlib.sha256(tokens).hexdigest() != digest):
                continue
            binaries[stage][uid] = tokens
            missing[stage].remove(uid)
            aliases.append({'kind': 'unique_checksum_match_in_scanned_assets',
                            'stage': stage, 'uid': uid, 'sha256': digest,
                            'source_uid': candidate['source_uid'],
                            'zone': candidate['zone'], 'offset': candidate['offset'],
                            'bytes': len(tokens), 'occurrences': candidate['occurrences']})


def extract(app, output, skip_fastfiles=False):
    resources = app / 'Contents/Resources'
    recipe_files = sorted(resources.glob('*.glslcache.plist'))
    binary_files = sorted(resources.glob('*.bincache.plist'))
    if not recipe_files or len(binary_files) != 1:
        raise ValueError('Expected MW3 recipe plists and exactly one bundled bincache plist')
    output.mkdir(parents=True, exist_ok=True)
    pairs = {}
    recipes_by_file = {}
    for path in recipe_files:
        data = plistlib.loads(path.read_bytes())
        if data.get('CacheVersion') != 2:
            raise ValueError('Unsupported recipe version: ' + str(path))
        file_pairs = set()
        for records in data['VS'].values():
            for entry in records:
                key = tuple(entry[field] for field in ('vsUID', 'psUID', 'vsKey', 'psKey'))
                if len(key[2]) != 32 or len(key[3]) != 32:
                    raise ValueError('Unexpected shader recipe key size')
                pairs[key] = entry
                file_pairs.add(key)
        recipes_by_file[path.name] = file_pairs
    merged = {'CacheVersion': 2, 'VS': {}, 'PS': {}}
    for _, entry in sorted(pairs.items()):
        for stage, field in [('VS', 'vsUID'), ('PS', 'psUID')]:
            merged[stage].setdefault(entry[field], []).append(entry)
    binaries = plistlib.loads(binary_files[0].read_bytes())
    if binaries.get('CacheVersion') != 1:
        raise ValueError('Unsupported shader binary cache version')
    missing = {}
    aliases = []
    for stage in ('VS', 'PS'):
        by_hash = collections.defaultdict(list)
        for uid, tokens in binaries[stage].items():
            if not valid_tokens(tokens, stage) or int(uid.split(':', 1)[0], 16) != zlib.adler32(tokens):
                raise ValueError('Invalid bundled shader bytecode or UID: ' + uid)
            by_hash[uid.split(':', 1)[0]].append((uid, tokens))
        missing[stage] = set(merged[stage]) - binaries[stage].keys()
        for uid in sorted(missing[stage]):
            candidates = by_hash.get(uid.split(':', 1)[0], [])
            token_sets = {tokens for _, tokens in candidates}
            if len(token_sets) != 1:
                continue
            tokens = next(iter(token_sets))
            binaries[stage][uid] = tokens
            missing[stage].remove(uid)
            aliases.append({'stage': stage, 'uid': uid, 'source_uid': candidates[0][0],
                            'bytes': len(tokens), 'sha256': hashlib.sha256(tokens).hexdigest()})
    merged_path = output / 'all-recipes.glslcache.plist'
    binary_path = output / 'expanded.bincache.plist'
    merged_temporary = merged_path.with_suffix(merged_path.suffix + '.tmp')
    merged_temporary.write_bytes(plistlib.dumps(merged, fmt=plistlib.FMT_BINARY))
    merged_temporary.replace(merged_path)
    scans, extracted = [], []
    checksum_aliases, hash_candidates = [], {}
    target_hashes = {stage: {int(uid.split(':', 1)[0], 16) for uid in values}
                     for stage, values in missing.items()}

    def checkpoint():
        report = {'app': str(app), 'recipe_files': len(recipe_files),
                  'unique_recipes': len(pairs), 'unique_vs': len(merged['VS']),
                  'unique_ps': len(merged['PS']), 'aliases': aliases,
                  'extracted_missing_shaders': extracted, 'fastfile_scans': scans,
                  'checksum_targeted_aliases': checksum_aliases,
                  'checksum_target_ambiguities': [
                      {'stage': stage, 'checksum': f'{checksum:08x}',
                       'distinct_bytecodes': len(bucket), 'sha256': sorted(bucket)}
                      for (stage, checksum), bucket in sorted(hash_candidates.items())
                      if len(bucket) > 1],
                  'unresolved': {stage: sorted(values) for stage, values in missing.items()},
                  'covered_recipes': sum(vs in binaries['VS'] and ps in binaries['PS']
                                         for vs, ps, _, _ in pairs),
                  'recipe_file_coverage': [
                      {'file': name, 'recipes': len(entries),
                       'covered': sum(vs in binaries['VS'] and ps in binaries['PS']
                                      for vs, ps, _, _ in entries),
                       'missing_vs': sorted({vs for vs, _, _, _ in entries if vs not in binaries['VS']}),
                       'missing_ps': sorted({ps for _, ps, _, _ in entries if ps not in binaries['PS']})}
                      for name, entries in recipes_by_file.items()],
                  'outputs': {'merged_recipe': str(merged_path), 'expanded_binary': str(binary_path)}}
        # Replace complete files so other tools never read a partial plist.
        for path, content in [(binary_path, plistlib.dumps(binaries, fmt=plistlib.FMT_BINARY)),
                              (output / 'extraction-manifest.json',
                               (json.dumps(report, indent=2) + '\n').encode())]:
            temporary = path.with_suffix(path.suffix + '.tmp')
            temporary.write_bytes(content)
            temporary.replace(path)
        return report

    checkpoint()
    if not skip_fastfiles:
        zones = app / 'Contents/GameData/zone'
        english = sorted((zones / 'english').glob('*.ff'),
                         key=lambda path: (path.name != 'common.ff', path.name))
        dlc = sorted((zones / 'dlc').glob('*.ff'),
                     key=lambda path: (path.name.startswith(('german_', 'french_', 'spanish_', 'italian_')), path.name))
        for path in english + dlc:
            if not any(missing.values()) and not any(target_hashes.values()):
                break
            scans.append(scan_fastfile(path, missing, binaries, extracted,
                                       target_hashes, hash_candidates))
            checkpoint()
            print(path.name, 'resolved', scans[-1]['resolved'], 'remaining',
                  {stage: len(values) for stage, values in missing.items()}, flush=True)
    # Newly extracted code can satisfy additional recipe names with the same
    # checksum. Only alias unambiguous, byte-identical token streams.
    add_hash_aliases(binaries, missing, aliases)
    if not any(scan['error'] for scan in scans):
        add_scanned_checksum_aliases(binaries, missing, hash_candidates, checksum_aliases)
    report = checkpoint()
    print('Covered', report['covered_recipes'], 'of', report['unique_recipes'], 'recipes')
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--app', type=Path, required=True, help='MW3 app bundle to read')
    parser.add_argument('--output', type=Path, required=True, help='Directory for extracted local assets')
    parser.add_argument('--skip-fastfiles', action='store_true', help='Only merge recipes and verified binary aliases')
    args = parser.parse_args()
    app, output = args.app.resolve(), args.output.resolve()
    if output == app or app in output.parents:
        parser.error('Output directory must be outside the source app bundle')
    extract(app, output, args.skip_fastfiles)


if __name__ == '__main__':
    main()
