#!/usr/bin/env python3
"""Generates the loader's OpenGL dispatch: an exported x86_64 trampoline for
every gl* and CGL* function OpenGL.framework exports, each jumping through a
slot of lp32_gl_dispatch_table (filled by gl_backend.c from whichever OpenGL
implementation is selected).  The loader links against these instead of
OpenGL.framework, so both its own GL calls and dlsym(RTLD_DEFAULT, "gl...")
reach the selected implementation.

usage: gen_gl_dispatch.py <names>... --asm out.S --header out.h"""
import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("names", nargs="+")
    parser.add_argument("--asm", required=True)
    parser.add_argument("--header", required=True)
    args = parser.parse_args()
    names = []
    for path in args.names:
        names += [line.strip() for line in open(path) if line.strip()]
    names = sorted(set(names))
    with open(args.asm, "w") as asm:
        asm.write("/* Generated by tools/gen_gl_dispatch.py. */\n    .text\n")
        for i, name in enumerate(names):
            asm.write(f"    .globl _{name}\n    .p2align 3\n_{name}:\n")
            asm.write(f"    jmp *_lp32_gl_dispatch_table+{8 * i}(%rip)\n")
    with open(args.header, "w") as header:
        header.write("/* Generated by tools/gen_gl_dispatch.py. */\n")
        header.write(f"#define LP32_GL_DISPATCH_COUNT {len(names)}\n")
        header.write("static const char *const lp32_gl_dispatch_names[LP32_GL_DISPATCH_COUNT] = {\n")
        for name in names:
            header.write(f'    "{name}",\n')
        header.write("};\n")

if __name__ == "__main__":
    main()
