/* The threaded command stream: GL calls recorded on the application's
 * thread into per-context batches and executed by a worker thread, the way
 * Mesa's glthread works. Calls that return data, or read memory whose size
 * is unknown, drain the stream and run on the calling thread
 * (marshal.c is generated by tools/gen_marshal.py; see DESIGN.md). */
#ifndef GLM_THREAD_H
#define GLM_THREAD_H

#include <stddef.h>
#include <stdint.h>

#ifndef GLM_HIDDEN
#define GLM_HIDDEN __attribute__((visibility("hidden")))
#endif

struct glm_context;

/* Executes one recorded command; `payload` is what glm_thread_alloc gave. */
typedef void (*glm_exec_fn)(const void *payload);

/* Starts the worker for `ctx` (idempotent) / drains and stops it. */
GLM_HIDDEN void glm_thread_start(struct glm_context *ctx);
GLM_HIDDEN void glm_thread_stop(struct glm_context *ctx);
/* Room for a command of `size` payload bytes, executed by `exec`. */
GLM_HIDDEN void *glm_thread_alloc(struct glm_context *ctx, size_t size, glm_exec_fn exec);
/* Hands the current batch to the worker without waiting. */
GLM_HIDDEN void glm_thread_submit(struct glm_context *ctx);
/* Waits until every recorded command has executed. */
GLM_HIDDEN void glm_thread_sync(struct glm_context *ctx);
/* The same, counted per entry point for GLMETAL_STREAM_STATS. */
GLM_HIDDEN void glm_thread_sync_named(struct glm_context *ctx, const char *name);
/* State-changing commands recorded but not yet executed: while there are
   none, queries of that state can read the implementation directly. */
GLM_HIDDEN void glm_thread_state_recorded(struct glm_context *ctx);
GLM_HIDDEN void glm_thread_state_executed(struct glm_context *ctx);
GLM_HIDDEN int glm_thread_state_settled(struct glm_context *ctx);
/* The same counters by index: 0 state changes, 1 texture-object changes. */
GLM_HIDDEN void glm_thread_pending_add(struct glm_context *ctx, int which, int delta);
GLM_HIDDEN int glm_thread_pending_zero(struct glm_context *ctx, int which);

/* Commands recorded so far on this context (a mark for glm_thread_request). */
GLM_HIDDEN uint64_t glm_thread_recorded(struct glm_context *ctx);
/* Commands executed so far by the worker (compare with glm_thread_recorded). */
GLM_HIDDEN uint64_t glm_thread_executed(struct glm_context *ctx);
/* Runs `fn(arg)` on the worker as soon as the first `after` recorded
   commands have executed (ahead of later ones), and waits for it: queries
   that depend on a few commands need not drain the whole stream. Without a
   stream it runs now. */
GLM_HIDDEN void glm_thread_request(struct glm_context *ctx, uint64_t after, glm_exec_fn fn, const void *arg);

/* Presents are throttled: at most this many frames recorded ahead. */
GLM_HIDDEN void glm_thread_frame_recorded(struct glm_context *ctx);
GLM_HIDDEN void glm_thread_frame_executed(struct glm_context *ctx);

enum { GLM_MARSHAL_MAX = 64 << 10 }; /* larger pointer data is not copied: the call syncs */

#endif
