#!/usr/bin/env python3
"""Generates the headers glcompare cases include instead of OpenGL's.

Each gl* function the SDK header declares becomes a macro that calls through
the implementation the runner loaded:

    #define glClear ((__typeof__(&glClear))glc_resolve(17, "glClear"))

The macro names itself inside __typeof__, which the preprocessor does not
expand again, so the SDK's own declaration supplies the type. Cases keep
writing plain GL, and nothing binds to whichever libGL dyld finds first.

usage: gen_gl_header.py SDK OUTDIR
"""
import pathlib
import re
import sys


def declared_functions(paths):
    names = []
    seen = set()
    for path in paths:
        text = path.read_text(errors='replace')
        for name in re.findall(r'^\s*(?:extern|GLAPI)\s[^;]*?\b(gl[A-Z]\w*)\s*\(', text, re.M | re.S):
            if name not in seen:
                seen.add(name)
                names.append(name)
    return names


def main():
    sdk, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    headers = sdk / 'System/Library/Frameworks/OpenGL.framework/Headers'
    variants = {
        'glc_gl_legacy.h': ['gl.h', 'glext.h'],
        'glc_gl_core.h': ['gl3.h', 'gl3ext.h'],
    }
    per_file = {name: declared_functions([headers / h for h in files]) for name, files in variants.items()}
    ids = {}
    for names in per_file.values():
        for name in names:
            ids.setdefault(name, len(ids))
    out.mkdir(parents=True, exist_ok=True)
    for filename, names in per_file.items():
        guard = filename.upper().replace('.', '_')
        lines = [f'/* Generated by gen_gl_header.py from the macOS SDK. */', f'#ifndef {guard}', f'#define {guard}',
                 '#define GL_SILENCE_DEPRECATION 1']
        lines += [f'#include <OpenGL/{h}>' for h in variants[filename]]
        lines += ['#include "glcompare.h"',
                  'void *glc_resolve(int id, const char *name);']
        lines += [f'#define {n} ((__typeof__(&{n}))glc_resolve({ids[n]}, "{n}"))' for n in names]
        lines += ['#endif', '']
        (out / filename).write_text('\n'.join(lines))
    (out / 'glc_gl_count.h').write_text(f'#define GLC_GL_FUNCTION_COUNT {len(ids)}\n')


if __name__ == '__main__':
    main()
