#!/usr/bin/env python3
"""Generates the injector's interposing tables: for every export of Apple's
OpenGL.framework (gl* and CGL*), a trampoline that jumps through a table
filled with GLMetal's implementation, and a __DATA,__interpose tuple that
makes dyld send the application's calls to that trampoline.

  gen_inject.py OUT_DIR apple-gl-exports.txt apple-cgl-exports.txt
"""
import pathlib
import sys

out = pathlib.Path(sys.argv[1])
names = []
for path in sys.argv[2:]:
    names += [line.strip() for line in open(path) if line.strip() and not line.startswith('#')]
names = sorted(set(names))
out.mkdir(parents=True, exist_ok=True)

asm = ['// Generated by tools/gen_inject.py. Trampoline i jumps through', '// _glm_inject_table[i].', '.text']
for i, name in enumerate(names):
    asm += [f'.globl _glm_inject_{name}', '.private_extern _glm_inject_' + name, '.p2align 2', f'_glm_inject_{name}:',
            '#if defined(__x86_64__)', f'    jmp *(_glm_inject_table+{8 * i})(%rip)',
            '#else', '    adrp x16, _glm_inject_table@PAGE', '    add x16, x16, _glm_inject_table@PAGEOFF',
            f'    ldr x16, [x16, #{8 * i}]', '    br x16', '#endif']
(out / 'inject_trampolines.S').write_text('\n'.join(asm) + '\n')

c = ['/* Generated by tools/gen_inject.py. */', '#include <stddef.h>', '',
     f'#define GLM_INJECT_COUNT {len(names)}', 'void *glm_inject_table[GLM_INJECT_COUNT];', '',
     'const char *const glm_inject_names[GLM_INJECT_COUNT] = {']
c += [f'    "{n}",' for n in names]
c += ['};', '']
for n in names:
    c.append(f'extern void glm_apple_{n}(void) __asm("_{n}");')
    c.append(f'extern void glm_inject_{n}(void);')
c += ['', 'struct interpose { const void *replacement, *replacee; };',
      '__attribute__((used, section("__DATA,__interpose"))) static const struct interpose interposers[] = {']
c += [f'    {{(const void *)glm_inject_{n}, (const void *)glm_apple_{n}}},' for n in names]
c += ['};', '', '/* Apple\'s implementation of entry i, for lookups that bypass binding. */',
      'const void *const glm_inject_apple[GLM_INJECT_COUNT] = {']
c += [f'    (const void *)glm_apple_{n},' for n in names]
c += ['};', 'const size_t glm_inject_count = GLM_INJECT_COUNT;']
(out / 'inject_tables.c').write_text('\n'.join(c) + '\n')
