#!/usr/bin/env python3
"""Generates attrib_setters.c: every immediate-mode attribute entry point
(glVertex*, glColor*, glNormal*, glTexCoord*, glMultiTexCoord*,
glSecondaryColor*, glFogCoord*, glVertexAttrib*) as a thin wrapper around
glm_attrib(), with GL 2.1's integer-to-float conversions (table 2.9).

usage: gen_attribs.py OUTPUT
"""
import sys

TYPES = {
    # suffix: (C type, GL type, normalized conversion)
    'b': ('GLbyte', 'GLbyte', '(2.0f * (float)({v}) + 1.0f) / 255.0f'),
    's': ('GLshort', 'GLshort', '(2.0f * (float)({v}) + 1.0f) / 65535.0f'),
    'i': ('GLint', 'GLint', '(float)((2.0 * (double)({v}) + 1.0) / 4294967295.0)'),
    'f': ('GLfloat', 'GLfloat', '(float)({v})'),
    'd': ('GLdouble', 'GLdouble', '(float)({v})'),
    'ub': ('GLubyte', 'GLubyte', '(float)({v}) / 255.0f'),
    'us': ('GLushort', 'GLushort', '(float)({v}) / 65535.0f'),
    'ui': ('GLuint', 'GLuint', '(float)((double)({v}) / 4294967295.0)'),
}

out = ['/* Generated by tools/gen_attribs.py. */', '#include "glm_internal.h"', '',
       'GLM_HIDDEN void glm_attrib(int slot, float x, float y, float z, float w);',
       'GLM_HIDDEN void glm_generic_attrib(GLuint index, float x, float y, float z, float w);', '']
emitted = set()


def emit(name, params, body):
    if name in emitted:
        return
    emitted.add(name)
    out.append(f'GLM_EXPORT void {name}({params}) {{ {body} }}')


def family(prefix, sizes, suffixes, slot_expr, normalize, defaults, extra_param='', extra_arg='', aliases=()):
    """aliases: extension suffixes (glSecondaryColor3fEXT)."""
    names = 'xyzw'
    for n in sizes:
        for suffix in suffixes:
            ctype, _, conv = TYPES[suffix]
            convert = (lambda v: conv.format(v=v)) if normalize else (lambda v: f'(float)({v})')
            args = [convert(names[i]) for i in range(n)] + defaults[n:]
            argsv = [convert(f'v[{i}]') for i in range(n)] + defaults[n:]
            params = ', '.join([p for p in [extra_param] if p] + [f'{ctype} {names[i]}' for i in range(n)])
            paramsv = ', '.join([p for p in [extra_param] if p] + [f'const {ctype} *v'])
            for ext in ('', *aliases):
                emit(f'{prefix}{n}{suffix}{ext}', params, f'glm_attrib({slot_expr}, {", ".join(args)});')
                emit(f'{prefix}{n}{suffix}v{ext}', paramsv, f'glm_attrib({slot_expr}, {", ".join(argsv)});')


DEFAULT = ['0.0f', '0.0f', '0.0f', '1.0f']
family('glVertex', [2, 3, 4], ['s', 'i', 'f', 'd'], 'GLM_ATTR_POSITION', False, DEFAULT)
family('glColor', [3, 4], ['b', 's', 'i', 'f', 'd', 'ub', 'us', 'ui'], 'GLM_ATTR_COLOR', True, DEFAULT)
family('glSecondaryColor', [3], ['b', 's', 'i', 'f', 'd', 'ub', 'us', 'ui'], 'GLM_ATTR_SECONDARY_COLOR', True,
       ['0.0f', '0.0f', '0.0f', '1.0f'], aliases=('EXT',))
family('glTexCoord', [1, 2, 3, 4], ['s', 'i', 'f', 'd'], 'GLM_ATTR_TEX0', False, DEFAULT)
family('glMultiTexCoord', [1, 2, 3, 4], ['s', 'i', 'f', 'd'], 'GLM_ATTR_TEX0 + (int)((target - GL_TEXTURE0) & 7)', False,
       DEFAULT, extra_param='GLenum target')

# glMultiTexCoord*ARB aliases.
for n in [1, 2, 3, 4]:
    for suffix in ['s', 'i', 'f', 'd']:
        ctype = TYPES[suffix][0]
        names = 'xyzw'
        params = ', '.join(['GLenum target'] + [f'{ctype} {names[i]}' for i in range(n)])
        emit(f'glMultiTexCoord{n}{suffix}ARB', params,
             f'glMultiTexCoord{n}{suffix}(target{"".join(", " + names[i] for i in range(n))});')
        emit(f'glMultiTexCoord{n}{suffix}vARB', f'GLenum target, const {ctype} *v', f'glMultiTexCoord{n}{suffix}v(target, v);')

# Normals use the colour conversion for integer types.
for suffix in ['b', 's', 'i', 'f', 'd']:
    ctype, _, conv = TYPES[suffix]
    c = lambda v: conv.format(v=v)
    emit(f'glNormal3{suffix}', f'{ctype} x, {ctype} y, {ctype} z', f'glm_attrib(GLM_ATTR_NORMAL, {c("x")}, {c("y")}, {c("z")}, 0.0f);')
    emit(f'glNormal3{suffix}v', f'const {ctype} *v', f'glm_attrib(GLM_ATTR_NORMAL, {c("v[0]")}, {c("v[1]")}, {c("v[2]")}, 0.0f);')

for suffix in ['f', 'd']:
    ctype = TYPES[suffix][0]
    for ext in ('', 'EXT'):
        emit(f'glFogCoord{suffix}{ext}', f'{ctype} x', 'glm_attrib(GLM_ATTR_FOG, (float)x, 0.0f, 0.0f, 1.0f);')
        emit(f'glFogCoord{suffix}v{ext}', f'const {ctype} *v', 'glm_attrib(GLM_ATTR_FOG, (float)v[0], 0.0f, 0.0f, 1.0f);')

# Generic vertex attributes, core and ARB names.
names = 'xyzw'
for arb in ('', 'ARB'):
    for n in [1, 2, 3, 4]:
        for suffix in ['s', 'f', 'd']:
            ctype = TYPES[suffix][0]
            args = [f'(float){names[i]}' for i in range(n)] + DEFAULT[n:]
            argsv = [f'(float)v[{i}]' for i in range(n)] + DEFAULT[n:]
            emit(f'glVertexAttrib{n}{suffix}{arb}', ', '.join(['GLuint index'] + [f'{ctype} {names[i]}' for i in range(n)]),
                 f'glm_generic_attrib(index, {", ".join(args)});')
            emit(f'glVertexAttrib{n}{suffix}v{arb}', f'GLuint index, const {ctype} *v', f'glm_generic_attrib(index, {", ".join(argsv)});')
    for suffix in ['b', 'i', 'ub', 'us', 'ui']:
        ctype = TYPES[suffix][0]
        emit(f'glVertexAttrib4{suffix}v{arb}', f'GLuint index, const {ctype} *v',
             'glm_generic_attrib(index, (float)v[0], (float)v[1], (float)v[2], (float)v[3]);')
    for suffix in ['b', 's', 'i', 'ub', 'us', 'ui']:
        ctype, _, conv = TYPES[suffix]
        c = lambda v: conv.format(v=v)
        emit(f'glVertexAttrib4N{suffix}v{arb}', f'GLuint index, const {ctype} *v',
             f'glm_generic_attrib(index, {c("v[0]")}, {c("v[1]")}, {c("v[2]")}, {c("v[3]")});')
    emit(f'glVertexAttrib4Nub{arb}', 'GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w',
         'glm_generic_attrib(index, x / 255.0f, y / 255.0f, z / 255.0f, w / 255.0f);')

open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
