#!/usr/bin/env python3
"""Generates glm_apple_profile.h from the Apple reference dump
(data/apple-gl-reference.txt, written by tools/apple_dump.c
against Apple's OpenGL.framework): strings, extensions and limits per
profile, so GLMetal reports exactly what Apple's implementation reports.

usage: gen_profile.py REFERENCE OUTPUT
"""
import sys


def main(reference, output):
    sections, current = {}, None
    for line in open(reference):
        line = line.rstrip('\n')
        if line.startswith('[') and line.endswith(']'):
            current = sections.setdefault(line[1:-1], {})
        elif '=' in line and current is not None:
            key, value = line.split('=', 1)
            current[key] = value
    out = ['/* Generated by tools/gen_profile.py from the Apple reference dump. */',
           '#ifndef GLM_APPLE_PROFILE_H', '#define GLM_APPLE_PROFILE_H', '',
           'struct glm_limit { unsigned pname; int count; double values[4]; };', '']
    for name in ('legacy', 'core'):
        s = sections[name]
        # "2.1 Metal - 90.5": the renderer build suffix follows the version.
        out.append(f'static const char glm_{name}_version[] = "{s["VERSION"]}";')
        out.append(f'static const char glm_{name}_glsl[] = "{s["GLSL"]}";')
        out.append(f'static const char *const glm_{name}_extensions[] = {{')
        out += [f'    "{e}",' for e in s['EXTENSIONS'].split() if e]
        out.append('    0,\n};')
        out.append(f'static const struct glm_limit glm_{name}_limits[] = {{')
        # LIMIT.<pname>.<name>=values: every implementation-dependent value
        # Apple answers in this profile (tools/apple_dump.c).
        for k, v in s.items():
            if not k.startswith('LIMIT.'):
                continue
            _, pname, limit_name = k.split('.', 2)
            values = [float(x) for x in v.split()][:4]
            if limit_name == 'MAX_SERVER_WAIT_TIMEOUT':
                continue  # 64-bit; answered in context.c
            out.append(f'    {{{pname} /* {limit_name} */, {len(values)}, {{{", ".join(repr(x) for x in values)}}}}},')
        out.append('    {0, 0},\n};')
        out.append(f'static const unsigned glm_{name}_renderer_id = {s["RENDERER_ID"]};')
        out.append('')
    out.append('#endif')
    open(output, 'w').write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
