#!/usr/bin/env python3
"""Generates stubs.c: a weak definition of every function Apple's
OpenGL.framework exports (data/apple-*-exports.txt, tools/gen_exports.py). GLMetal's real
implementations are strong definitions and replace them at link time; the
rest report themselves once and raise GL_INVALID_OPERATION, so the library
always exports Apple's complete symbol set.

usage: gen_stubs.py OUTPUT EXPORTS...
"""
import sys

names = []
for path in sys.argv[2:]:
    names += [line.strip() for line in open(path) if line.strip()]
out = ['/* Generated by tools/gen_stubs.py. No GL headers: signatures are irrelevant',
       '   to weak fallbacks that ignore their arguments and return 0. */',
       '#include <stdint.h>',
       'void glm_unimplemented(const char *name);']
for name in sorted(set(names)):
    out.append(f'__attribute__((weak, visibility("default"))) uintptr_t {name}(void) '
               f'{{ glm_unimplemented("{name}"); return 0; }}')
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
