#!/usr/bin/env python3
"""Builds glm_apple_gets.h from data/apple-get-reference.txt (written by
tools/apple_get_sweep.c): per profile, every glGet pname Apple's OpenGL
accepts, sorted, with the values a new context returns.

usage: gen_get_reference.py apple-get-reference.txt out.h"""
import sys

rows = {"legacy": [], "core": []}
caps = {"legacy": [], "core": []}
renderbuffers = {"legacy": [], "core": []}
textures = {"legacy": [], "core": []}
for line in open(sys.argv[1]):
    if line.startswith("#") or not line.strip():
        continue
    parts = line.split()
    if parts[0].endswith("-tex"):
        # x (a GL error: luminance/intensity pnames in core) reads as 0.
        v = [0 if p == "x" else int(p, 16) if i in (0, 1) or 11 <= i <= 17 or i in (19, 20) or i >= 27 else int(p)
             for i, p in enumerate(parts[1:])]
        textures[parts[0][:-4]].append(v)
        continue
    if parts[0].endswith("-rb"):
        renderbuffers[parts[0][:-3]].append([int(parts[1], 16), int(parts[2], 16)] + [int(v) for v in parts[3:9]])
        continue
    if parts[0].endswith("-cap"):
        caps[parts[0][:-4]].append((int(parts[1], 16), int(parts[2])))
        continue
    rows[parts[0]].append((int(parts[1], 16), [int(v) for v in parts[3:3 + int(parts[2])]]))
with open(sys.argv[2], "w") as out:
    out.write("/* Generated by tools/gen_get_reference.py from data/apple-get-reference.txt. */\n")
    out.write("struct glm_apple_get { unsigned short pname; unsigned char count; int values[16]; };\n")
    out.write("struct glm_apple_renderbuffer { unsigned short format, reported; unsigned char bits[6]; };\n")
    out.write("/* glGetTexLevelParameteriv of a 2D level, and as a framebuffer attachment. */\n"
              "struct glm_apple_texture { unsigned short format, reported; unsigned char size[9]; /* r g b a l i d s shared */\n"
              "    unsigned short type[7]; /* r g b a l i d */ unsigned char compressed; unsigned short encoding, component;\n"
              "    unsigned char attachment[6]; /* r g b a d s */\n"
              "    unsigned short status[3]; /* glCheckFramebufferStatus alone as colour 0, depth, stencil */ };\n")
    out.write("struct glm_apple_cap { unsigned short cap; unsigned char settable; };\n")
    out.write("#ifndef GLM_APPLE_TYPES_ONLY\n")
    for profile, entries in rows.items():
        entries.sort()
        out.write(f"static const struct glm_apple_get glm_apple_gets_{profile}[] = {{\n")
        for pname, values in entries:
            out.write(f"    {{0x{pname:04x}, {len(values)}, {{{', '.join(map(str, values[:16])) or '0'}}}}},\n")
        out.write("};\n")
    for profile, entries in renderbuffers.items():
        entries.sort()
        out.write(f"static const struct glm_apple_renderbuffer glm_apple_renderbuffers_{profile}[] = {{\n")
        for e in entries:
            out.write(f"    {{0x{e[0]:04x}, 0x{e[1]:04x}, {{{', '.join(map(str, e[2:]))}}}}},\n")
        out.write("};\n")
    for profile, entries in textures.items():
        entries.sort()
        out.write(f"static const struct glm_apple_texture glm_apple_textures_{profile}[] = {{\n")
        for e in entries:
            hexes = lambda xs: ", ".join(f"0x{x:04x}" for x in xs)
            out.write(f"    {{0x{e[0]:04x}, 0x{e[1]:04x}, {{{', '.join(map(str, e[2:11]))}}}, {{{hexes(e[11:18])}}}, {e[18]}, "
                      f"0x{e[19]:04x}, 0x{e[20]:04x}, {{{', '.join(map(str, e[21:27]))}}}, {{{hexes(e[27:30])}}}}},\n")
        out.write("};\n")
    for profile, entries in caps.items():
        entries.sort()
        out.write(f"static const struct glm_apple_cap glm_apple_caps_{profile}[] = {{\n")
        for cap, settable in entries:
            out.write(f"    {{0x{cap:04x}, {settable}}},\n")
        out.write("};\n")
    out.write("#endif\n")
