#!/usr/bin/env python3
"""Generates glm_core_enums.h: every GL_* constant gl3.h/gl3ext.h define that
the legacy gl.h/glext.h pair lacks. GLMetal implements both profiles in one
library but Apple's two header sets cannot be included together.

usage: gen_core_enums.py SDK OUTPUT
"""
import pathlib
import re
import sys

sdk, output = pathlib.Path(sys.argv[1]), sys.argv[2]
headers = sdk / 'System/Library/Frameworks/OpenGL.framework/Headers'
lines = ['/* Generated by tools/gen_core_enums.py from gl3.h and gl3ext.h. */',
         '#ifndef GLM_CORE_ENUMS_H', '#define GLM_CORE_ENUMS_H']
seen = set()
for name in ('gl3.h', 'gl3ext.h'):
    for macro, value in re.findall(r'^#define\s+(GL_[A-Z0-9_x]+)\s+(\S+)\s*$', (headers / name).read_text(), re.M):
        if macro in seen or not re.match(r'^(0x[0-9A-Fa-f]+[uU]?[lL]*|\d+[uU]?[lL]*|\(?[A-Z0-9_]+\)?)$', value):
            continue
        seen.add(macro)
        lines += [f'#ifndef {macro}', f'#define {macro} {value}', '#endif']
lines.append('#endif')
open(output, 'w').write('\n'.join(lines) + '\n')
