#!/usr/bin/env python3
"""Generates the exported gl* entry points of LP32GL.

Every name OpenGL.framework exports (data/apple-gl-exports.txt, taken from
the SDK's libGL.tbd) becomes a symbol that jumps through a table slot.  The
slots start at a stub and are filled with lp32gl_get_proc_address() results
on first use, so a program linked against LP32GL instead of OpenGL.framework
finds every function it could have imported."""
import sys

def main(names_path, asm_path, c_path):
    names = [n.strip() for n in open(names_path) if n.strip()]
    with open(asm_path, "w") as asm:
        asm.write("/* Generated by tools/gen_exports.py. */\n")
        asm.write("#if defined(__x86_64__)\n")
        asm.write("    .text\n")
        for i, name in enumerate(names):
            asm.write(f"    .globl _{name}\n    .p2align 3\n_{name}:\n")
            asm.write(f"    jmp *_lp32gl_export_table+{8 * i}(%rip)\n")
        asm.write("#elif defined(__aarch64__)\n")
        asm.write("    .text\n")
        for i, name in enumerate(names):
            asm.write(f"    .globl _{name}\n    .p2align 2\n_{name}:\n")
            asm.write("    adrp x16, _lp32gl_export_table@PAGE\n")
            asm.write("    add x16, x16, _lp32gl_export_table@PAGEOFF\n")
            asm.write(f"    ldr x16, [x16, #{8 * i}]\n    br x16\n")
        asm.write("#endif\n")
    with open(c_path, "w") as c:
        c.write("/* Generated by tools/gen_exports.py. */\n")
        c.write("#include <stddef.h>\n\n")
        c.write(f"#define LP32GL_EXPORT_COUNT {len(names)}\n")
        c.write("static const char *const lp32gl_export_names[LP32GL_EXPORT_COUNT] = {\n")
        for name in names:
            c.write(f'    "{name}",\n')
        c.write("};\n")

if __name__ == "__main__":
    main(*sys.argv[1:4])
