#!/usr/bin/env python3
"""Generates lp32gl_apple_profile.h from data/apple-gl-reference.txt, the
output of tools/apple_dump.c run against Apple's OpenGL.framework."""
import sys

def main(reference, output):
    sections = {}
    current = None
    for line in open(reference):
        line = line.rstrip("\n")
        if line.startswith("[") and line.endswith("]"):
            current = sections.setdefault(line[1:-1], {})
        elif "=" in line and current is not None:
            key, value = line.split("=", 1)
            current[key] = value
    with open(output, "w") as out:
        out.write("/* Generated by tools/gen_apple_profile.py from data/apple-gl-reference.txt. */\n")
        out.write("#ifndef LP32GL_APPLE_PROFILE_H\n#define LP32GL_APPLE_PROFILE_H\n\n")
        out.write("struct lp32gl_limit { unsigned pname; int value; };\n\n")
        for name in ("legacy", "core"):
            s = sections[name]
            exts = [e for e in s["EXTENSIONS"].split() if e]
            out.write(f"static const char *const apple_{name}_extensions[] = {{\n")
            for e in exts:
                out.write(f'    "{e}",\n')
            out.write("    0,\n};\n")
            out.write(f'static const char apple_{name}_glsl[] = "{s["GLSL"]}";\n')
            limits = [(k, v) for k, v in s.items() if k.startswith("MAX_") and int(v) > 0]
            out.write(f"static const struct lp32gl_limit apple_{name}_limits[] = {{\n")
            for k, v in limits:
                out.write(f"    {{GL_{k}, {v}}},\n")
            out.write("    {0, 0},\n};\n\n")
        out.write("#endif\n")

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
